### ISSUE TITLE
make ends with errors

### ISSUE THREAD

**Issue by Gintarelis** [lvht/nginx-websocket-module#2]
/root/nginx-websocket-module/ngx_http_websocket_module.c
/root/nginx-websocket-module/ngx_http_websocket_module.c: In function ‘ngx_http_ws_get_addrinfo’:
/root/nginx-websocket-module/ngx_http_websocket_module.c:279:12: error: missing initializer for field ‘ai_flags’ of ‘struct addrinfo’ [-Werror=missing-field-initializers]
     struct addrinfo hints = {};
            ^
In file included from src/os/unix/ngx_linux_config.h:48:0,
                 from src/core/ngx_config.h:26,
                 from /root/nginx-websocket-module/ngx_http_websocket_module.c:1:
/usr/include/netdb.h:569:7: note: ‘ai_flags’ declared here
   int ai_flags;   /* Input flags.  */
       ^
/root/nginx-websocket-module/ngx_http_websocket_module.c: In function ‘ngx_http_ws_send_push_token’:
/root/nginx-websocket-module/ngx_http_websocket_module.c:683:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (struct addrinfo *p = srv_ctx->addrs; p != NULL; p = p->ai_next) {
     ^
/root/nginx-websocket-module/ngx_http_websocket_module.c:683:5: note: use option -std=c99 or -std=gnu99 to compile your code
/root/nginx-websocket-module/ngx_http_websocket_module.c: In function ‘ngx_http_ws_conf’:
/root/nginx-websocket-module/ngx_http_websocket_module.c:743:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (ngx_uint_t n = 1; n < cf->args->nelts; n++) {
     ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/nginx-websocket-module/ngx_http_websocket_module.o] Error 1
make[1]: Leaving directory `/root/nginx-1.15.9'
make: *** [build] Error 2

**Comment by taoso** [comment]
please try according this note
> /root/nginx-websocket-module/ngx_http_websocket_module.c:683:5: note: use option -std=c99 or -std=gnu99 to compile your code
